- coreos-meta-translator/trans.py
Add additional logging to help with CI / debugging.
Addresses #10
> coreos-meta-translator: add additional logging

- COPYING
- LICENSE
This is the same one as fedora-coreos-config (MIT).
Closes: #11
> Add license

- coreos-meta-translator/trans.py
> coreos-meta-translator: add live ISO and PXE images

- coreos-koji-tagger/coreos_koji_tagger.py
In the event that the app goes down or misses a message, it's important
that we sync up with the latest state on restart. Otherwise, we might be
unsynced until the next fedmsg comes along.
Closes: #51
> coreos-koji-tagger: process lockfiles on startup

- coreos-meta-translator/trans.py
Adds the GCP artifacts to the `release.json`.
Closes #56
> coreos-meta-translator: add gcp artifacts

- coreos-koji-tagger/coreos_koji_tagger.py
The coreos-koji-tagger is a long running process. If koji gets restarted
then we end up with a stale session and we won't make any progress.
Let's try to re-auth if we ever get a denial.
Fixes: https://github.com/coreos/fedora-coreos-releng-automation/issues/46
> coreos-koji-tagger: re-auth if koji get's restarted

- config-bot/manifest.yaml
This makes it easier to view/delete all the objects related to the app
in one shot.
> config-bot: add `app` label

- coreos-meta-translator/trans.py
For now, just the artifacts. We're not yet uploading to those clouds.
> coreos-meta-translator: add aliyun and azure

- coreos-ostree-importer/coreos_ostree_importer.py
If a request comes in for a commit that:
- is for a ref that doesn't exist yet in the repo
- has no parent
then allow it to be created. If it doesn't meet those criteria,
then error out.
> coreos-ostree-importer: handle creating new refs in the repo

- coreos-ostree-importer/coreos_ostree_importer.py
We need to optimize os.walk() here because it can take a really
long time to find all the directories on the NFS mounts because
it must look at every file and there are many many files in the
directories under `objects/*/`. Here we'll optmize for the fact
that we know `objects/*` are directories and `objects/*/*` are normal
files so we don't need to traverse deeper.
> coreos-ostree-importer: optimize os.walk

- coreos-meta-translator/trans.py
coreos-meta-translator: add Exoscale
https://github.com/coreos/fedora-coreos-tracker/issues/384
> coreos-meta-translator: add Exoscale

- scripts/download-overrides.py
This should help us catch issues in the overrides file in CI. See
https://github.com/coreos/fedora-coreos-config/pull/293.
> scripts: check epoch match for overrides files entry

- coreos-meta-translator/trans.py
Depends on https://github.com/coreos/fedora-coreos-stream-generator/pull/9.
> coreos-meta-translator: add digitalocean

- coreos-ostree-importer/send-ostree-import-request.py
The importer is fully up and running now, so let's start checking that
it correctly imported the commit and error out if an error occurred.
> importer: start validating response from service

- coreos-ostree-importer/coreos_ostree_importer.py
Sometimes we do multiple builds in a stream before we release one
(i.e. if we found a problem before release). Each new build will
have a parent commit corresponding to the last *released* build,
which is the correct thing to do. In that case our parent commit
check won't be valid, so let's only do that check on the prod repo.
As part of this I moved the sanity checks out of ostree_pull_local
so I could use the target_repo variable without having to change
the function call signature of ostree_pull_local.
> coreos-ostree-importer: only do parent commit check on prod repo

- .cci.jenkinsfile
- coreos-koji-tagger/coreos_koji_tagger.py
- run-pylint
Let's do a pylint run on the repo so we can catch basic stuff like
missing variables or functions, etc...
> Hook up repo to CoreOS CI and run pylint

- scripts/download-overrides.py
See e.g. https://github.com/coreos/fedora-coreos-config/pull/489.
>  download-overrides: handle empty overrides 

- coreos-koji-tagger/coreos_koji_tagger.py
- scripts/download-overrides.py
commit 2a80a80998cf8421be53c4cc5b10a355f3258b55
Date:   Tue Mar 9 17:06:52 2021 -0500
coreos-koji-tagger: pre-calculate archful lockfile names
Rather than a nested loop, use a nested function and call out to it to
construct the archful lockfile names.
Patch best viewed with whitespace ignored.
commit a433d74dd254bc631bcb1415849e6063b66647f0
Date:   Tue Mar 9 17:10:44 2021 -0500
coreos-koji-tagger: add support for new arch-independent override
In coreos-assembler, we're adding support for a new
`manifest-lock.overrides.yaml` file:
https://github.com/coreos/coreos-assembler/pull/2075
Make sure the tagger knows to read from it and tag the packages in there
into the pool.
commit f5bac955839914b90d64391f1d2f3cd7dc91f138
Date:   Thu Mar 11 16:40:51 2021 -0500
scripts/download-overrides.py: add …
> Teach coreos-koji-tagger and download-overrides.py about new archless overrides lockfile 

- scripts/broadcast-fedmsg.py
We've decided to add the arch to the stream_release fedmsg as well.
> broadcast-fedmsg: add arch to stream_release fedmsg

- config-bot/Dockerfile
> config-bot/Dockerfile: update to F36

- config-bot/Dockerfile
- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
Fedora 37 has been released so let's move our containers to be based on it.
> updates for Fedora 37

- fedora-ostree-pruner/fedora-ostree-pruner
Now that the 2022 end of year holidays are over let's go ahead and prune!
> fedora-ostree-pruner: enable pruning the prod OSTree repo

- config-bot/Dockerfile
- config-bot/main
See: https://github.com/coreos/fedora-coreos-releng-automation/issues/164
> config-bot/main: Replace toml with tomllib

- fedora-ostree-pruner/fedora-ostree-pruner
We'll switch it back to Saturday soon.
> fedora-ostree-pruner: switch to Friday so we can run a test today

- fedora-ostree-pruner/fedora-ostree-pruner
Also have a second commit in there which adds a log message.
> fedora-ostree-pruner: switch back to Saturday

- scripts/promote-config.sh
See: https://github.com/coreos/fedora-coreos-releng-automation/pull/178
> scripts/promote-config.sh: Restore kola-denylist.yaml

- coreos-ostree-importer/Dockerfile
See: https://github.com/coreos/fedora-coreos-tracker/issues/1490
> Dockerfile: update to F39

- config-bot/Dockerfile
- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
- fedora-ostree-pruner/Dockerfile
Fedora 40 has released, lets update the dockerfiles to f40.
See : https://github.com/coreos/fedora-coreos-tracker/issues/1674
> config-bot/Dockerfile: Move to Fedora 40

- fedora-ostree-pruner/fedora-ostree-pruner
xref: https://pagure.io/workstation-ostree-config/pull-request/578
> fedora-ostree-pruner: Add new `cosmic` Atomic Desktop
