coreos/fedora-coreos-releng-automation

- config-bot/Dockerfile
- config-bot/README.md
- config-bot/config.toml
- config-bot/main
- config-bot/manifest.yaml
config-bot performs automated management tasks on the main
[fedora-coreos-config](https://github.com/coreos/fedora-coreos-config) repo.
See `README.md` for details.
> tree: add new config-bot service

- coreos-meta-translator/README.md
- coreos-meta-translator/trans.py
Originally discussed in https://github.com/arithx/meta-transpiler/pull/1
Tested against both `plume` & the `fedora-coreos-stream-generator`
> coreos-meta-translator: initial commit

- coreos-meta-translator/trans.py
In coreos/coreos-assembler#580 the `archs` key of builds.json was
updated to be `arches`.
> coreos-meta-translator: update archs to arches

- coreos-koji-tagger/coreos_koji_tagger.py
Since it's built in a module it the normal heuristic doesn't work.
Fixes #7
> coreos-koji-tagger: add target release heuristic for zincati

- config-bot/main
We need to teach config-bot to read from the new build layout format
with support for multi-arch. Prep for enabling lockfiles.
> config-bot: adapt for new build layout

- coreos-koji-tagger/coreos_koji_tagger.py
The rpm-ostree lockfile format was changed in:
https://github.com/projectatomic/rpm-ostree/commit/b670ab37c2bb62d8515ff2fd4196612fa27a1420
Adapt coreos-koji-tagger to work with it.
> coreos-koji-tagger: update for new lockfile format

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
Start listening for git pushes on
https://github.com/coreos/fedora-coreos-config instead of
https://pagure.io/dusty/coreos-koji-data.
This notably involves switching out the topic we listen to, and
introspecting the message. We could use the `commit[].modified[]` values
here to be even more selective, but leaving that for a follow-up.
> coreos-koji-tagger: point at fedora-coreos-config repo

- scripts/promote-config.sh
This script can be used to promote changes from `testing-devel` to
`testing` before a release. Ideally, it would be called from a job, but
for now, we can at least run it manually.
> scripts: add promote-config.sh script

- coreos-koji-tagger/Dockerfile
I've hit issues where the container was out of date and some things
were slightly broken. One case of this: https://pagure.io/releng/compose-tracker/pull-request/21
> coreos-koji-tagger: get latest updates in Dockerfile

- coreos-koji-tagger/coreos_koji_tagger.py
This should make it easier to test in fedora's stage environment.
Also switch to `os.getenv`
> coreos-koji-tagger: ability to override github repo

- coreos-koji-tagger/coreos_koji_tagger.py
Raise an Exception object instead of a bare raise.
Fixes #21
> coreos-koji-tagger: get rid of bare raise

- coreos-koji-tagger/coreos_koji_tagger.py
These make the logs a little too verbose.
> coreos-koji-tagger: comment out a few debug statements

- coreos-koji-tagger/coreos_koji_tagger.py
Use a list rather than starting with a string and converting
to a list. Will help prevent any outside input from adding
new components to the command that will be run.
Fixes #24
> coreos-koji-tagger: switch to using list to define commands

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
This PR will convert us to using the koji python library. There are several
other small commits in this PR that can be reviewed separately. The
commit summary is:
- move to koji python library
- find_principal_from_keytab no longer class function
- convert some log statements to info
- wait for tagging tasks to complete
- no more bare raises
- catch exceptions and continue
> coreos-koji-tagger: move to koji python library

- coreos-koji-tagger/README.md
This should give someone an idea on how to go about testing the
koji tagger in Fedora's staging OpenShift.
> coreos-koji-tagger: Update README with docs on Staging Environment

- config-bot/config.toml
We're in position to enable lockfile promotion now that
coreos-koji-tagger is set up and monitoring the `testing-devel` branch.
Let's do this!
> config-bot: enable promote-lockfiles

- coreos-koji-tagger/coreos_koji_tagger.py
The lockfile is located at `manifest-lock.x86_64.json` on
`testing-devel`. The `.generated` one was from a test message that was
actually for `bodhi-updates`.
> coreos-koji-tagger: fix manifest lockfile filename

- coreos-koji-tagger/coreos_koji_tagger.py
Use a more general pattern for recognizing buildroot tags so that we
don't have to keep adding exceptions.
> coreos-koji-tagger: generalize module buildroot tags regex

- config-bot/config.toml
This reverts commit 9a38dd3ef8dc6810e7935c99a3cdffc8ddb152e3.
There are a few more kinks to be worked out with this whole process.
Let's disable lockfile promotion until we can get them completely
worked out.
> Revert "config-bot: enable promote-lockfiles"

- config-bot/main
`testing-devel` dropped the `overlay/` dir in favour of `overlay.d`.
However, we weren't deleting the `overlay/` dir in `bodhi-updates`
during file propagation. Make it so that it's like an `rsync --delete`.
> config-bot: fix propagate-files logic for deleted files

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/README.md
- coreos-koji-tagger/coreos_koji_tagger.py
Add support for the other lockfiles and a few other fixups:
- coreos-koji-tagger: move commit var access lower
- coreos-koji-tagger: Update README with more staging docs
- coreos-koji-tagger: add support for other architectures
- coreos-koji-tagger: support overrides files
- coreos-koji-tagger: remove koji 1.18 workaround
> coreos-koji-tagger: add support for overrides and multi-arch lockfiles

- coreos-koji-tagger/coreos_koji_tagger.py
Otherwise you might not get much in the way of log statements to begin
with and might wonder if things are running.
> coreos-koji-tagger: add startup log statement

- config-bot/main
- scripts/promote-config.sh
That way we know exactly what content from what commit was propagated.
Similarly, in the promotion script, include the commit that was
promoted.
Hat tip to Colin who suggested this during a review of the FCOS release
process.
> config-bot: include source ref checksum used in commit message

- coreos-koji-tagger/Dockerfile
- Clean up a few copy/paste errors from compose-tracker
- We are now using the Consumer module
- Make a few comments more generic so the diff between other
Dockerfiles will be smaller.
> coreos-koji-tagger: cleanups in Dockerfile

- coreos-meta-translator/trans.py
Adding arch extensions to artifact filenames caused the translator to produce artifact keys like `x86_64.qcow2.xz` instead of `qcow2.xz`.  Fix this.
Fixes #47.  Fixes coreos/fedora-coreos-stream-generator#4.
> coreos-meta-translator: keep arch extensions out of artifact keys

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
- coreos-koji-tagger: add a catch_exceptions_and_continue decorator
- coreos-koji-tagger: logging.warn is deprecated
- coreos-koji-tagger: switch to fedora 31
> coreos-koji-tagger: move to f31 and add catch_exceptions_and_continue decorator

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/README.md
- coreos-koji-tagger/coreos_koji_tagger.py
- coreos-koji-tagger: update instructions for testing in stage
- coreos-koji-tagger: rework test setup using Mock
- coreos-koji-tagger: support yaml lockfiles
> coreos-koji-tagger: support yaml lockfiles

- coreos-koji-tagger/coreos_koji_tagger.py
- coreos-koji-tagger: timeout waiting for signing after 10 minutes
- coreos-koji-tagger: call distrepo manually
> coreos-koji-tagger: call distrepo manually

- coreos-koji-tagger/coreos_koji_tagger.py
This shouldn't happen, but we'll return early if we couldn't detect
any desired rpms from the lockfiles in the repo.
> coreos-koji-tagger: return early if no desiredrpms detected

- scripts/download-overrides.py
I intend to use this to close the gap we have in upstream CI testing
when adding overrides:
https://github.com/coreos/fedora-coreos-releng-automation/issues/32#issuecomment-541134070
> scripts: add download-overrides.py

- coreos-koji-tagger/coreos_koji_tagger.py
In our logic to determine if we're still logged in we need to catch
the koji.AuthError exception and pass so that we can fall through to
the code that does the login.
This is a followup to d46a3a1 which was part of
https://github.com/coreos/fedora-coreos-releng-automation/issues/46
> coreos-koji-tagger: catch koji.AuthError exception

- scripts/versionary.py
This script implements the versioning scheme as described in:
coreos/fedora-coreos-tracker#211
The next step is to use this in the FCOS pipeline to drive versioning.
> scripts: add versionary.py to drive FCOS versioning

- coreos-ostree-importer/Dockerfile
- coreos-ostree-importer/README.md
- coreos-ostree-importer/coreos_ostree_importer.py
We'll send the messages with a plain http(s) url so that this importer
doesn't need to be configured with AWS credentials.
> coreos-ostree-importer: switch to plain http(s) url

- config-bot/Dockerfile
- config-bot/main
I think we're hitting an issue somewhere where git can get stuck trying
to fetch from the remote, if e.g. GitHub is being flaky. We should
probably add some timeouts/retries, though for now at least let's add
some logging to make it easier to tell what's going on.
> config-bot: add some more logging

- coreos-ostree-importer/README.md
- coreos-ostree-importer/coreos_ostree_importer.py
- coreos-ostree-importer/fedora-messaging-config.toml
- coreos-ostree-importer/send-ostree-import-request.py
There are various improvements to the ostree importer in this patchset, including
the addition of send-ostree-import-request.py. Please see individual commit
messages for more information.
> coreos-ostree-importer: various improvements; add requester script

- coreos-ostree-importer/coreos_ostree_importer.py
- coreos-ostree-importer/fedora-messaging-config.toml
A few fixes/updates to the coreos-ostree-importer code.
-  coreos-ostree-importer: add passive_declares to the config
- coreos-ostree-importer: add comment to top of the config file
- coreos-ostree-importer: detect the message topic from the config
- coreos-ostree-importer: fix example message payload
> coreos-ostree-importer: misc fixes

- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
Rather than hit our fedora servers 2 or 3 times for the metadata let's
just let the cache bake in the images.
> Dockerfiles: remove the `dnf clean all` where it doesn't make sense

- coreos-ostree-importer/Dockerfile
- coreos-ostree-importer/coreos-ostree-importer-wrapper
- coreos-ostree-importer/coreos_ostree_importer.py
We are going to be running two applications with access to the ostree repos:
`coreos-ostree-importer` and `fedora-ostree-pruner`. In order to do this in
OpenShift we need everything to be group writable. This PR sets the umask
such that new files are creating group writable and also adds a check to make
sure that directories in the repo have the group writable bit set.
> coreos-ostree-importer: configure/check for group writable 

- coreos-ostree-importer/Dockerfile
- coreos-ostree-importer/coreos_ostree_importer.py
This can be useful for testing or if we ever need to manually trigger
imports if the importer fails for any reason like:
- there was a failure when importing a previous version and we want to trigger a new import
- the importer was down and not able to respond to a previous request
Should be able to execute like:
./coreos_ostree_importer.py 'https://apps.fedoraproject.org/datagrepper/id?id=2020-32c268dc-36ba-4cef-be6a-f4969a0c83af&is_raw=true&size=extra-large'
> coreos-ostree-importer: support manual runs with datagrepper URL inputs

- coreos-ostree-importer/coreos_ostree_importer.py
Only create/update a summary file if we are targeting the prod
OSTree repo. The compose repo doesn't use a summary file (i.e.
robosig updates the files under ./refs/heads) and it causes problems
if the summary file exists.
> coreos-ostree-importer: only update summary file for prod repo

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
We're hitting this pretty frequently in prod now. Let's try retrying for
a bit in case it's simply due to Koji restarting or something.
See: https://github.com/coreos/fedora-coreos-releng-automation/issues/70
> coreos-koji-tagger: retry koji login for 15m

- scripts/versionary.py
We don't need to do this anymore now:
https://github.com/coreos/rpm-ostree/commit/37a6a3ab696050548578fb15650cbea6540484be
> versionary: stop creating OSTree repo for --print-only

- coreos-meta-translator/trans.py
For https://github.com/coreos/fedora-coreos-tracker/issues/385.
> coreos-meta-translator: add metal4k support

- config-bot/config.toml
For now we inherit from testing-devel; see discussions starting from:
https://github.com/coreos/fedora-coreos-config/pull/180#issuecomment-534697400
> config-bot: enable propagate-files for next-devel

- coreos-koji-tagger/coreos_koji_tagger.py
Generalize things a bit so that we can monitor multiple branches, then
add next-devel to the list.
> coreos-koji-tagger: handle both testing-devel and next-devel

- coreos-ostree-importer/coreos_ostree_importer.py
We need to update a few pieces to set their umask to 0002 when modifying
files in the repos. robosignatory and pungi are two that still need to
be updated. For now let's just print the warnings and not error out.
> coreos-ostree-importer: remove permissions check for now

- config-bot/config.toml
bodhi-updates is down, so disable lockfile syncing so we don't override
manual lockfile bumps we will do for now.
https://github.com/coreos/fedora-coreos-config/pull/335#issuecomment-610634917
> config-bot: disable sync-build-lockfiles

- scripts/versionary.py
As per https://github.com/coreos/fedora-coreos-config/pull/351.
Otherwise, it's (quite rightly) not happy to use the "unlocked"
semantics for versioning.
This will automatically error out again once we add lockfiles back in,
so we'll definitely not forget to drop this hack.
> versionary: temporarily mark next-devel and next as unlocked

- config-bot/config.toml
Otherwise every time we'll try to manually bump the testing-devel
lockfile, it'll create a diff from bodhi-updates which config-bot will
want to reconcile.
> config-bot: disable promote-lockfiles too

- coreos-ostree-importer/Dockerfile
Grab ostree-2020.3-3.fc31 from koji so we can hopefully get over
some concurrency issues. https://github.com/ostreedev/ostree/pull/2077
> coreos-ostree-importer: use newer ostree from koji

- coreos-ostree-importer/send-ostree-import-request.py
This is a followup to c92a36e. We need to define the response variable.
> coreos-ostree-importer: fix send-import-request response validation

- coreos-ostree-importer/send-ostree-import-request.py
Should fix the pipeline currently hitting:
> NameError: name 'send_request_and_wait_for_response' is not defined
> importer: import send_request_and_wait_for_response function

- coreos-ostree-importer/coreos_ostree_importer.py
- coreos-ostree-importer/send-ostree-import-request.py
This should give the importer enough time to actually process and
do the import. The current default timeout of 1 minute is not enough.
Also fixed a bug (see first commit).
> coreos-ostree-importer: update send request timeout

- coreos-ostree-importer/coreos_ostree_importer.py
More bugs introduced by 49cb095. Now we have properly changed
the variables to the names they should be in the higher context.
> coreos-ostree-importer: fix more variable bugs

- scripts/versionary.py
This reverts commit ccae9dc994c65b324320fef014bd5337e3d46c7c.
We don't need this anymore since we've added lockfiles back to
`next-devel` in https://github.com/coreos/fedora-coreos-config/pull/370.
(The `next` stream doesn't yet have lockfiles, but the next release
there should since we'll be promoting from `next-devel`.)
> Revert "versionary: temporarily mark next-devel and next as unlocked"

- config-bot/config.toml
Since it's dead right now anyway.
> config-bot: disable propagate-files for bodhi-updates

- coreos-meta-translator/trans.py
* Consider Vultr generic images when translating meta to release
> coreos-meta-translator: Add Vultr to trans.py

- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
- coreos-ostree-importer/coreos-ostree-importer-wrapper
With the switch to f32 the version of python is now 3.8 so the
`/usr/lib/python3.7/site-packages/` path we were using previously
no longer works. Since fedora-messaging now supports providing
a path directly to a file via `--callback-file`, let's use that
behavior instead.
> Switch fedora-messaging based apps to use --callback-file

- coreos-ostree-importer/Dockerfile
https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/18
Drop when it hits stable:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-4ba7f57a90
> coreos-ostree-importer: use new OSTree with EOPNOTSUPP fix

- coreos-meta-translator/trans.py
As AMIs have their own field `images` under the `aws` key, I think it might make sense for GCP to follow the same rule, adding an `image` field under the `gcp` key and rename the original `image` key to `name`.
If this is reasonable, it should be followed by updating `fedora-coreos-stream-generator` to support this PR. Finally, download page could read the GCP cloud launchable metadata from e.g. `stable.json` instead of `meta.json`
Related: https://github.com/coreos/fedora-coreos-tracker/issues/494
Signed-off-by: Allen Bai <abai@redhat.com>
> coreos-meta-translator: add gcp cloud launchable to release.json

- coreos-ostree-importer/coreos_ostree_importer.py
If a previous import failed, we want to be able to rerun it. However,
the rerun exits early right now because it sees the commit and thinks
that it's fully there.
Make it also check that the commit is not marked as partial.
> coreos-ostree-importer: handle partial commits

- coreos-ostree-importer/Dockerfile
Since that version hit bodhi stable we can go back to tracking latest.
This reverts commit 39a98ff5c9b11611340a0fc10c16b9baf262d45b.
> coreos-ostree-importer: use latest ostree from stable repos

- coreos-meta-translator/trans.py
For https://github.com/coreos/fedora-coreos-tracker/issues/390.
Example output:
```json
{
"release": "32.20200719.dev.0",
"stream": "testing-devel",
"architectures": {
"x86_64": {
"media": {
"metal": {
"artifacts": {
"raw": {
"disk": {
"location": "https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/32.20200719.dev.0/x86_64/fedora-coreos-32.20200719.dev.0-metal.x86_64.raw",
"signature": "https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/32.20200719.dev.0/x86_64/fedora-coreos-32.20200719.dev.0-metal.x86_64.raw.sig",
"sha256": "d4a7e2f48a6a2437d8ed5d2f9e7d5a269cd894081169b7e2757f885c5f2ce377"
}
},
"4k.raw": {
"disk": {
"location": "https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/32.20200719.dev.0/x86_64/fedora-coreos-32. …
```
> coreos-meta-translator: add PXE rootfs image

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
We've tried to work around the issue in #70 several ways including
d46a3a1, a90d53d, and 286612b. Nothing seems to be working and we are
currently still at https://github.com/coreos/fedora-coreos-releng-automation/issues/70#issuecomment-600820800.
Restarting the pod seems to work well enough so let's just self destruct
if we detect this failure case. The new pod that gets created will
do a scan of the repos and pick up right where the old one left off
so this should work just fine.
> coreos-koji-tagger: detonate pod if we get a koji auth error

- coreos-koji-tagger/Dockerfile
We're seeing gssapi auth issues with the latest Koji update. There is an
upstream issue describing a bug in `requests-gssapi` not working well
with the Koji rollout:
https://pagure.io/koji/issue/2422
Our error is not exactly the same, though I see the same symptom
described in:
https://pagure.io/koji/issue/2422#comment-669723
where the principal used has extra appended data to it:
```
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): Can't find client principal coreos-koji-tagger\/coreos-koji-tagger.fedoraproject.org/fedoraproject.org@FEDORAPROJECT.ORG in cache collection
```
There is a Bodhi update to the package which should fix this. Let's
cherry-pick it for now to unblock FCOS releases.
> coreos-koji-tagger: cherry-pick latest python3-requests-gssapi

- coreos-koji-tagger/Dockerfile
coreos-koji-tagger: remove locked python3-requests-gssapi
This was added in 82f27e3. The package is in the bodhi stable repos
now so we can go back to not pulling it directly from koji.
https://bodhi.fedoraproject.org/updates/FEDORA-2020-134329dd96
> coreos-koji-tagger: remove locked python3-requests-gssapi

- config-bot/main
First, don't implicitly fetch all the latest commits when acquiring a
`Git` context; let's make it a separate `fetch()` function.
Second, handle errors from fetching that could be due to networking
flakes or e.g. GitHub being down. We want `config-bot` to just absorb
all transient errors and retry.
> config-bot: handle flakes from GitHub when fetching

- coreos-release-notes-generator/README.md
- coreos-release-notes-generator/release-notes-generator.py
This script generates Fedora CoreOS release note from pre-mature release note snippets. Takes two arguments: `--config-dir` and `--output-dir`.
The `config_dir` is the directory where a `'release-notes.d` directory resides, typically a `fedora-coreos-config` directory, which has pre-mature release notes yaml snippets.
The `output_dir` is the directory where a `release-notes.yaml` resides. If there's no such file then a new file will be created. If a `release-notes.yaml` already exists, then checks if the `next-release` field is present in the file. It inserts the `next-release` field to the front of the file if none is present or updates the existing `next-release` field if one already exists.
Related: https://github.com/coreos/fedora-coreos-tracker/issues/194
Signed-off-by: Allen Bai …
> coreos-release-notes-generator: init script for generating release notes

- config-bot/README.md
- config-bot/manifest.yaml
```
commit 60e4489d8c53c4abbcb25595a0697220ad76be6d
Date:   Wed Aug 26 15:40:42 2020 -0400
config-bot/manifest: use same GitHub coreosbot secret as pipeline
Since we're deployed in the same namespace anyway, might as well reuse
the same secret.
commit bdfde294b4758bf88ef093f13982414dd6159e58
Date:   Wed Aug 26 15:41:11 2020 -0400
config-bot/README: add details about deploying to OpenShift
Pretty straight-forward, but just to have it written down somewhere.
```
> config-bot: a few tweaks following migration to OCP4 cluster

- scripts/broadcast-fedmsg.py
This is a thin wrapper around the new `broadcast_fedmsg` function:
https://github.com/coreos/coreos-assembler/pull/1821
This is the script to which the Fedora CoreOS pipelines will call out.
> scripts: add broadcast-fedmsg.py

- scripts/broadcast-fedmsg.py
Otherwise it will require services which want to make use of these
fedmsgs to hardcode knowledge of our bucket layout. Don't make it
required so we can ratchet it in.
> broadcast-fedmsg: put build dir URL in build.state.change msg

- config-bot/config.toml
We'll try for now to keep using testing-devel as the source config ref
for rawhide builds. We can adapt in the future if it gets too tricky.
> config-bot: propagate files from testing-devel to rawhide

- config-bot/config.toml
Let's just stay with the theme of `testing-devel` being the source ref
for now.
> config-bot: propagate files from testing-devel to branched

- config-bot/config.toml
We now have `image-base.yaml` and `image.yaml`, where the latter is only
meant for a specific stream, while the former is shared. For more
information, see:
https://github.com/coreos/fedora-coreos-tracker/issues/292#issuecomment-806099932
https://github.com/coreos/coreos-assembler/pull/2096
https://github.com/coreos/fedora-coreos-config/pull/908
> config-bot: don't sync image.yaml

- config-bot/README.md
- config-bot/manifest.yaml
All config-bot needs is cloning and pushing. Let's use a separate token
for that from the more powerful github-coreosbot-token.
> config-bot/manifest.yaml: use separate token for config-bot

- coreos-koji-tagger/coreos_koji_tagger.py
We want to be able to pin packages in rawhide to keep things green while
we work with upstreams to get fixes applied.
> coreos-koji-tagger: watch/tag override lockfile from the rawhide branch

- coreos-koji-tagger/coreos_koji_tagger.py
We'll be using `branched` soon for f35 (after branching occurs). Let's
watch those lockfiles too.
> coreos-koji-tagger: watch/tag override lockfile from the branched branch

- coreos-koji-tagger/coreos_koji_tagger.py
For the first time ever we decided to fast-track a package directly
to testing/next rather than have it go through testing-devel first.
This meant the tagger didn't pick up and have the package signed/tagged.
Let's monitor our production branches too.
> coreos-koji-tagger: add monitoring of our production branches

- coreos-ostree-importer/send-ostree-import-request.py
This will allow us to send messages to import aarch64 commits
even if we're running in a x86_64 environment.
> coreos-ostree-importer: support passing in target architecture

- coreos-koji-tagger/coreos_koji_tagger.py
We just hit the case where a lot of packages needed to be tagged, and
there was genuine progress being made but the timer ran out. So then I
had to manually run `koji dist-repo`.
Let's just bump the timeout to 30 minutes to catch this.
A smarter method we could follow-up with on this would be to check if
the difference is getting smaller and reset the timeout if so.
> coreos-koji-tagger: bump signing timeout to 30 mins

- coreos-ostree-importer/Dockerfile
It's needed for `rpm-ostree ex-container import`. Else
you'll get an error like:
```
Importing ostree-unverified-image:oci-archive:/tmp/tmpi4g6huq7/ostree-archive:
Fetching manifest: Failed to exec skopeo: No such file or directory
```
> coreos-ostree-importer: add skopeo to package set

- config-bot/README.md
- config-bot/manifest.yaml
> config-bot: add README instructions to create secret token and drop BuildConfig GitHub trigger

- scripts/promote-config.sh
If e.g. you're hacking on `testing-devel` locally and then want to test
`next-devel` with those changes as if they were propagated by the bot,
you can use this.
> scripts/promote-config: add `LOCAL` for local hacking

- config-bot/README.md
- config-bot/manifest.yaml
This reverts commit a36ed742946f79371d7ea6c9f98d273280af6b37.
This should work again now that the API server is public:
https://pagure.io/fedora-infrastructure/issue/10521
> Revert "config-bot: drop BuildConfig GitHub trigger"

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/README.md
- coreos-ostree-importer/Dockerfile
- coreos-ostree-importer/README.md
```
commit 358af5fd09c810c6ecfd9895055b4bd1d5250fd2
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Thu Apr 21 16:55:02 2022 -0400
coreos-koji-tagger: move to F36 and migrate to new cluster
We migrated to the new OpenShift v4 cluster in Fedora's
infrastructure and rebased to Fedora 36 in the process.
Also updated a few links from cgit to pagure that should have
been updated previously.
commit be05f3bb0bce50b445ed0daacd368e0c3693401a
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Thu Apr 21 16:53:30 2022 -0400
coreos-ostree-importer: move to F36 and migrate to new cluster
We migrated to the new OpenShift v4 cluster in Fedora's
infrastructure and rebased to Fedora 36 in the process.
```
> Updates for tagger and importer

- config-bot/config.toml
`next` will lead `testing` by four releases.
> config-bot: temporarily skip syncing `platforms.yaml`

- config-bot/manifest.yaml
Those fields are only useful if instantiating the template itself, which
we're not doing here.
This is similar to what was done in:
https://github.com/coreos/fedora-coreos-pipeline/pull/582
My main motivation though is to get a commit in so that we can test that
https://pagure.io/fedora-infrastructure/issue/10603 is resolved.
> config-bot/manifest.yaml: remove unnecessary fields

- coreos-ostree-importer/coreos_ostree_importer.py
It's been a while now since we've switch to OCI archives for all our streams. Let's drop support for the previous tarball path.
> coreos-ostree-importer: drop support for tarballs

- coreos-ostree-importer/coreos_ostree_importer.py
The latter is deprecated now.  I noticed this in the code motion from
https://github.com/coreos/fedora-coreos-releng-automation/pull/158/commits/9ed720ed10caf6c56a6a507a32813a5ab54a6faf
> importer: Use `ostree container`, not `rpm-ostree ex-container`

- config-bot/config.toml
Once `platforms.yaml` promotes to `testing-devel`, we will no longer need it to diverge across our development branches.
Reverts #153.
> Revert "config-bot: temporarily skip syncing platforms.yaml"

- .cci.jenkinsfile
- fedora-ostree-pruner/Dockerfile
- fedora-ostree-pruner/README.md
- fedora-ostree-pruner/fedora-ostree-pruner
This will be run in Fedora's infrastructure and will prune out OSTree
repos that are used to serve content to Fedora users.
> add fedora-ostree-pruner

- fedora-ostree-pruner/fedora-ostree-pruner
We need to define it before we use it.
> fedora-ostree-pruner: move catch_exceptions function to the top

- fedora-ostree-pruner/fedora-ostree-pruner
In the container inside openshift they are at a specific location. Let's delete the two override lines I was using during testing that are the wrong location for the container.
> fedora-ostree-pruner: fix the location of the repos in the filesystem

- fedora-ostree-pruner/fedora-ostree-pruner
```
commit 5690b6bc17e1decfd30d0061217b62400e049fae
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed Dec 14 10:16:39 2022 -0500
fedora-ostree-pruner: drop hardcoding of test mode; limit to compose repo
We're in a position right now where we need to recover some space but
Kevin Fenzi is out on a much deserved break. Let's make this script
start taking real action by unsetting `args.test = True`, but let's
be conservative and only operate on the compose repo for now until
Kevin gets back.
In the most recent test this got us 1.2T in space back:
```
Total objects: 10768149
Would delete: 7437430 objects, freeing 1.2 TB
```
commit 575b0b1af63bb25f50d21418d30787043ce87208
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed Dec 14 10:14:53 2022 -0500
fedora-ostree-pruner: add ppc64le and …
```
> fedora-ostree-pruner: drop hardcoding of test mode; limit to compose repo

- scripts/promote-config.sh
For our production streams we don't want tests that weren't originally run for the original promotion to start running later (either on an ad-hoc build or for `stable` a few weeks later). Let's strip out the snooze lines when we do the promotion.
> scripts/promote-config: don't promote snoozes in denylist

- fedora-ostree-pruner/fedora-ostree-pruner
Let's not operate on aliased refs. Rather than require the person
who comes up with the configuration to understand what is an alias
and what isn't let's just do the right thing in the code.
We've seen an issue (we think) where a ref gets deleted and then
running `ostree summary -u` fails and we think it has to do with
operating on aliased refs. Let's find out.
> fedora-ostree-pruner: skip over aliased refs

- coreos-ostree-importer/Dockerfile
- fedora-ostree-pruner/Dockerfile
Sometimes we use the pods for the importer and pruner to inspect and fix issues with the OSTree repos since it's the most efficient way for us to gain read/write access to the repos. Recently I was restoring some data that was lost in a recent prune [1] and the `ostree pull` operation I was running failed with an obscure error message:
```
error: Commit 1eb251bced7652f2f486c15447a7bf00238ef0ea172b4f214d2684ecfbeb2c40:
GPG: GPG: Failed to import key: GPGME: System error w/o errno
```
It turns out the many gpg processes that get forked during a pull operation to verify the signatures for the commits don't get cleaned up:
```
1000720+   11737       1  0 14:59 pts/4    00:00:00 [gpg] <defunct>
1000720+   11740       1  0 14:59 pts/4    00:00:00 [gpg] <defunct>
1000720+   11743       1  0 …
```
> use dumb-init for the coreos-ostree-importer and fedora-ostree-pruner

- .cci.jenkinsfile
See: https://github.com/coreos/fedora-coreos-releng-automation/issues/164
> cci.jenkinsfile: Modify jenkinsfile to stop installing python3-toml

- scripts/promote-config.sh
warn: true was added in https://github.com/coreos/coreos-assembler/pull/3539 and can be used to make test failures non-fatal in the pipeline. Let's strip those from the denylist too on promotion.
> scripts/promote-config: strip warn: out of denylist on promotion

- config-bot/config.toml
This reverts commit cad1c9303e4f51ae4e781467d6acca206726fcca.
As mentioned in https://github.com/coreos/fedora-coreos-tracker/issues/1446#issuecomment-1693823642 we don't really need it anymore.
> Revert "config-bot: also sync new `experimental` branch"

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
For the Bodhi testing work, when testing a rawhide update, we want to
test against a known working rawhide build. To do this, we want to base
our build on the last working rawhide combination. We do this by reusing
the generated lockfile from that build and the git commit of the config
repo.
But for this to work, we need to make sure that we have access to all
the RPMs in that build.
This patch teaches coreos-koji-tagger to listen to the
`coreos.stream.release` fedmsg that the release job emits to know
when a new rawhide build is available; it then downloads the generated
lockfiles and tags in the packages.
Closes: #181
> coreos-koji-tagger: tag packages from rawhide builds into pool

- coreos-koji-tagger/Dockerfile
See: https://github.com/coreos/fedora-coreos-tracker/issues/1490
> coreos-koji-tagger/Dockerfile: move to Fedora 39

- config-bot/Dockerfile
- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
- fedora-ostree-pruner/Dockerfile
See: https://github.com/coreos/fedora-coreos-tracker/issues/1695
Bump the following Dockerfiles to `fedora:41`
- config-bot
- coreos-koji-tagger
- coreos-ostree-importer
- fedora-ostree-pruner
> various CoreOS tools: Update to Fedora 41

- fedora-ostree-pruner/fedora-ostree-pruner
This will make sure that messages are in the logs and also I think now that we have proper alerting we'll get an alert when pods exit because of an Exception like this.
> fedora-ostree-pruner: do repo checks on initial startup too

- scripts/promote-config.sh
The `--recurse-submodules` option to `git reset` only works if there are already submodules to recurse into. In the case where we're promoting from one branch which has a submodule to one which doesn't, this will not cause a git submodule directory to be created. Instead, we need to explicitly initialize potential new submodules.
We also need to handle the case where the submodule did exist but it was bumped by the promotion and so we need to update it.
Calling `git submodule update --init` handles both cases.
> scripts/promote-config: fix git submodule handling

- fedora-ostree-pruner/fedora-ostree-pruner
The refactor in b1662ac caused prod_refs variable to no longer be defined in the prune_prod_repo() function.
> fedora-ostree-pruner: fix issue from recent refactor

- fedora-ostree-pruner/fedora-ostree-pruner
This way we get a full picture of what refs are missing without having to guess if more are missing or not.
> fedora-ostree-pruner: check all refs before raising exception

- fedora-ostree-pruner/fedora-ostree-pruner
We've branched for 42 so those refs are in the repo now.
> fedora-ostree-pruner: add 42 to the stable list

- coreos-koji-tagger/coreos_koji_tagger.py
Been seeing a lot of `KeyError: 'ref'` lately so let's add some debugging to try to figure it out.
> coreos-koji-tagger: log when no ref in msg

- coreos-koji-tagger/coreos_koji_tagger.py
The schema of the message changed recently as explained to me:
> Oh yes the format has changed indeed, you'll find the content of the
> webhook in the "body" subkey, so message.body["body"]. The format change
> is annoying indeed, but it gives you access to the webhook headers, and
> lets the schema find out who is the agent of the change (for FMN).
> coreos-koji-tagger: Update for schema changes

- config-bot/Dockerfile
- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
- fedora-ostree-pruner/Dockerfile
Ref:https://github.com/coreos/fedora-coreos-tracker/issues/1851
Bump the following Dockerfiles to fedora:42
```
config-bot
coreos-koji-tagger
coreos-ostree-importer
fedora-ostree-pruner
```
> CoreOS tools: Update to Fedora 42

- config-bot/Dockerfile
- coreos-koji-tagger/Dockerfile
- coreos-ostree-importer/Dockerfile
- fedora-ostree-pruner/Dockerfile
Switch the builder stage from `registry.fedoraproject.org` to `quay.io/fedora/fedora:42` to align with common usage in container build workflows.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851
> Dockerfile: use quay.io as source for Fedora base image

- coreos-koji-tagger/Dockerfile
There is a new util-linux-core package that is the baseline in the F42 containerfile, but uuidgen (used in the Dockerfile for the build) didn't make the cut for the -core package so let's install the full util-linux.
> coreos-koji-tagger/Dockerfile: install util-linux

- coreos-koji-tagger/Dockerfile
- coreos-koji-tagger/coreos_koji_tagger.py
> coreos-koji-tagger: drop unique queue name; fix python syntax error

- coreos-koji-tagger/Dockerfile
In the previous fix I forgot to make this a -e sed and not -i for inplace edits, so the changes would go to stdout and populate my_config.toml.
Fixes da44a99
> coreos-koji-tagger/Dockerfile: fix another typo

- config-bot/README.md
These instructions should make it a little clearer and also updates the link to the documentation.
> config-bot: README: update to clarify setting up webook

- config-bot/config.toml
In the container-native path, `build-args.conf` becomes the new `manifest.yaml`. I.e. stream-specific arguments go in there. So they must not be synced across branches.
> config-bot: don't clobber build-args.conf

- config-bot/config.toml
Renovate uses the config from the repository's default branch. See [1] for more details.
It's a follow-up of [2]
[1] https://docs.renovatebot.com/configuration-options/
[2] https://github.com/coreos/fedora-coreos-config/pull/3613
> config-bot: don't clobber renovate.json

- fedora-ostree-pruner/fedora-ostree-pruner
We've branched for 43 so those refs are in the repo now.
> fedora-ostree-pruner: add 43 to the stable list, drop 40
